[package]
name = "navajo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = { version = "0.16", features = ["std"] }
prost = "0.11"
bytes = "1.3"

[build-dependencies]
prost-build = "0.11"
