[package]
name = "navajo-cli"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chance Dinkins"]
description = "Navajo CLI"

[[bin]]
name = "navajo"

[dependencies]
strum = { version = "0.24", features = ["derive", "strum_macros"] }
navajo = { path = "../navajo" }
clap = { version = "4.1", features = ["derive", "wrap_help"] }
tokio = { version = "1.26", features = ["full"] }
