[package]
name = "navajo"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chance Dinkins"]
description = "A Rust library for interacting with the Navajo API"

[dependencies]
bytes = "1.3.0"
futures = "0.3.25"
pin-project = "1.0.12"
ring = { version = "0.16.20", features = ["std"] }
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = "1.0.91"
zeroize = "1.5.7"

[dev-dependencies]
tokio = { version = "1.24", features = ["full"] } # todo: reduce features
