[package]
name = "navajo"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chance Dinkins"]

[dependencies]
ring = { version = "0.16", features = ["std"] }
bytes = "1.3.0"
hex = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_repr = "0.1"
tokio = { version = "1.24", features = ["full"] }  # todo: reduce features
zeroize = "1.5.7"
