[package]
name = "navajo"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chance Dinkins"]
description = "cryptographic APIs"

#cfg-if
[dependencies.cfg-if]

# futures
[dependencies.futures]
version = "0.3"

# time
[dependencies.time]
version = "0.3"

# pin-project
[dependencies.pin-project]
version = "1.0"

# rayon
[dependencies.rayon]
optional = true
version = "1.6"

# zeroize
[dependencies.zeroize]
version = "1.5"
features = ["alloc", "zeroize_derive", "serde"]

# hex -- TODO: may be able to remove this.
[dependencies.hex]
version = "0.4"
default-features = false
features = ["serde", "alloc"]

# paste
[dependencies.paste]
version = "1.0"

# hashbrown
[dependencies.hashbrown]
version = "0.13"

# rand
[dependencies.random]
package = "rand"
version = "0.8"


# serde
[dependencies.serde]
version = "1.0"
default-features = false
features = ["alloc", "derive", "rc"]

# serde_json
[dependencies.serde_json]
version = "1.0"
default-features = false
features = ["alloc"]

# serde_bytes
[dependencies.serde_bytes]
version = "0.11"

# ring
[dependencies.ring]
version = "0.16"
optional = true

# typenum
[dependencies.typenum]
features = ["no_std"]

# generic-array
[dependencies.generic-array]
version = "0.14.6"

# aes-siv
[dependencies.aes-siv]
version = "0.7"
optional = true

# crypto-common
[dependencies.crypto-common]
version = "0.1.6"

# chachapoly1305
[dependencies.chacha20poly1305]
version = "*"

# hmac -- TODO: remove this. hmac is provided in each impl
[dependencies.hmac]
version = "0.12"
optional = true

# aead
[dependencies.rust_crypto_aead]
version = "0.5"
package = "aead"

# aes-gcm
[dependencies.aes-gcm]
version = "0.10"
features = ["zeroize"]

# ed25519
[dependencies.ed25519]
version = "2.1"
default-features = false
features = ["pem", "zeroize", "serde"]
optional = true

# p256
[dependencies.p256]
version = "0.12"
features = ["ecdsa-core", "pkcs8", "hash2curve"]
optional = true

# p384
[dependencies.p384]
version = "0.12"
features = ["ecdsa-core", "pkcs8", "hash2curve"]
optional = true

# sha2
[dependencies.sha2]
version = "0.10"
optional = true

# sha3
[dependencies.sha3]
version = "0.10"
optional = true
default-features = false

# pkcs8
[dependencies.pkcs8]
version = "0.9"
default-features = false
optional = true

# pbkdf2
[dependencies.pbkdf2]
version = "0.11"

# aes 
[dependencies.aes]
features = ["zeroize"]
version = "0.8"
optional = true

# cmac
[dependencies.cmac]
version = "0.7"
features = ["zeroize"]
optional = true

# subtle
[dependencies.subtle]
version = "2.4"

# digest
[dependencies.digest]
version = "0.10"

# dbl
[dependencies.dbl]
version = "0.3"

# blake3
[dependencies.blake3]
version = "1.3"
optional = true

# bytes
[dependencies.bytes]
version = "1.4"

#hkdf
[dependencies.rust_crypto_hkdf]
package = "hkdf"
version = "0.12"


# -------------------------
#    Test dependencies
# -------------------------

# tokio
[dev-dependencies.tokio]
version = "1.14"
features = ["full"] # todo: reduce this.

[dev-dependencies.hex-literal]
version = "0.3"

[features]
default = [
	"std",
	"ring",
	"aead",
	"signature",
	"mac",
	"blake3",
	"hmac_sha2",
	"hmac_sha3",
	"cmac_aes",
]
hmac_sha2 = ["hmac", "sha2"]
hmac_sha3 = ["hmac", "sha3"]
cmac_aes = ["cmac", "aes"]
signature = ["ed25519", "p256", "p384"]
mac = ["rayon"]
aead = []
std = [
	"ring?/std",
	"hex/std",
	"serde/std",
	"serde_json/std",
	"zeroize/std",
	"aes-gcm/std",
	"aes-siv?/std",
	"hmac/std",
	"chacha20poly1305/std",
	"pkcs8?/std",
	"cmac/std",
	"digest/std",
	"sha2/std",
	"sha3/std",
]
