[package]
name = "navajo-gcp"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Chance Dinkins"]
description = "Navajo GCP KMS integration"

[dependencies]
kms-aead = { version = "0.12", features = ["gcp-kms-encryption"] }
navajo = { path = "../navajo" }
