name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.5.1
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
            - uses: taiki-e/install-action@cargo-hack
              with:
                  toolchain: nightly
                  override: true
            - name: Check
              run: cargo hack check --feature-powerset --no-dev-deps --workspace
            - name: Run tests
              run: cargo test --workspace --verbose
    coverage:
        runs-on: ubuntu-latest
        name: ubuntu / stable / coverage
        steps:
            - uses: Swatinem/rust-cache@v2.5.1
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Install nightly
              uses: dtolnay/rust-toolchain@nightly
              with:
                  components: llvm-tools-preview
            - name: rustup default nightly
              run: rustup default nightly
            # - name: cargo update -Zminimal-versions
            #   run: cargo +nightly update -Zminimal-versions
            - name: cargo install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: cargo generate-lockfile
              if: hashFiles('Cargo.lock') == ''
              run: cargo generate-lockfile
            - name: cargo llvm-cov
              run: cargo +nightly llvm-cov --locked --all-features --all --doctests --lcov --output-path lcov.info
            - name: Upload to codecov.io
              uses: codecov/codecov-action@v3
              with:
                  fail_ci_if_error: true
