name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
            - uses: taiki-e/install-action@cargo-hack
              with:
                  toolchain: nightly
                  override: true
            - name: Check
              run: cargo hack check --feature-powerset --no-dev-deps --workspace
            - name: Build
              run: cargo hack build --verbose --workspace

            - name: Run tests
              run: cargo test --workspace
              env:
                  CARGO_INCREMENTAL: "0"
                  RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
                  RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
            - name: rust-grcov
              uses: actions-rs/grcov@v0.1.5
            - name: Codecov
              uses: codecov/codecov-action@v3.1.0
              with:
                  verbose: true
                  fail_ci_if_error: true
